// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DatabaseFirst
{

    // Courses
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class Course
    {
        public int CourseId { get; set; } // CourseId (Primary key)
        public string Name { get; set; } // Name
        public string Credits { get; set; } // Credits

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Enrollment> Enrollments { get; set; } // Enrollments.FK_EnrollmentCourse

        public Course()
        {
            Enrollments = new System.Collections.Generic.List<Enrollment>();
        }
    }

}
// </auto-generated>
