// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DatabaseFirst
{

    // Enrollments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class Enrollment
    {
        public int EnrollmentId { get; set; } // EnrollmentId (Primary key)
        public int StudentStudentId { get; set; } // StudentStudentId
        public int CourseCourseId { get; set; } // CourseCourseId

        // Foreign keys
        public virtual Course Course { get; set; } // FK_EnrollmentCourse
        public virtual Student Student { get; set; } // FK_StudentEnrollment
    }

}
// </auto-generated>
