// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DatabaseFirst
{

    // Students
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class Student
    {
        public int StudentId { get; set; } // StudentId (Primary key)
        public string FirstName { get; set; } // FirstName
        public string LastName { get; set; } // LastName

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Enrollment> Enrollments { get; set; } // Enrollments.FK_StudentEnrollment

        public Student()
        {
            Enrollments = new System.Collections.Generic.List<Enrollment>();
        }
    }

}
// </auto-generated>
